# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftTest
pod 'Moya'
pod 'SwiftyJSON'
pod 'HandyJSON', '~> 5.0.0-beta.1'
pod 'SDCycleScrollView', '~> 1.80'
pod 'SnapKit', '~> 5.0.0'
pod 'Kingfisher', '~> 5.4.0'

end
